/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author tunki
 */
public class inpatientbillingform extends javax.swing.JFrame {

    private JFrame frame;

    /**
     * Creates new form inpatient
     */
    public inpatientbillingform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jAddButton = new javax.swing.JButton();
        jSaveButton = new javax.swing.JButton();
        jCloseButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPatientTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPatientID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPatientName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPatientAge = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jGenderComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jDateOfAdmission = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jDateOfDischarge = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jRoomCharges = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPatientID1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jDoctorFees = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPathology = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jMiscellanous = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPatientID2 = new javax.swing.JTextField();
        jTotalButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jDate = new javax.swing.JTextField();
        jBillNumber = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BILLING");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 20, 550, 60);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1370, 5));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 80, 1370, 10);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jAddButton.setBackground(new java.awt.Color(204, 255, 255));
        jAddButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jAddButton.setText("Add");
        jAddButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(jAddButton);
        jAddButton.setBounds(30, 20, 130, 40);

        jSaveButton.setBackground(new java.awt.Color(204, 255, 255));
        jSaveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSaveButton.setText("Save");
        jPanel3.add(jSaveButton);
        jSaveButton.setBounds(190, 20, 130, 40);

        jCloseButton1.setBackground(new java.awt.Color(153, 255, 255));
        jCloseButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCloseButton1.setText("Exit");
        jCloseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCloseButton1);
        jCloseButton1.setBounds(350, 20, 130, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(230, 560, 960, 70);

        jPatientTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BillNo", "Date", "Pid", "Name", "Age", "Gender", "Date of Admission", "Date of Discharge", "Room Charges", "Doctor Fees", "Pathology", "Miscellanous", "Total"
            }
        ));
        jScrollPane1.setViewportView(jPatientTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 630, 960, 100);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PATIENT DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jPatientID.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel22.setText("Name");

        jPatientName.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel21.setText("Age");

        jPatientAge.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel19.setText("Gender");

        jGenderComboBox.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female" }));
        jGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenderComboBoxActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel18.setText("Date Of Admission");

        jDateOfAdmission.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel20.setText("Date of Discharge");

        jDateOfDischarge.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel29.setText("ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(165, 165, 165)
                        .addComponent(jPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel29))
                        .addGap(149, 149, 149)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jDateOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jDateOfDischarge, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(137, 137, 137)
                        .addComponent(jGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19))
                    .addComponent(jLabel29)
                    .addComponent(jPatientID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel22))
                            .addComponent(jPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel21))
                            .addComponent(jPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18))
                            .addComponent(jDateOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel20))
                            .addComponent(jDateOfDischarge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(230, 140, 960, 200);

        jRoomCharges.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHARGES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel23.setText("Room Charges");

        jPatientID1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel24.setText("Doctor Fees");

        jDoctorFees.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel25.setText("Pathalogy");

        jPathology.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel28.setText("Miscellanous");

        jMiscellanous.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        javax.swing.GroupLayout jRoomChargesLayout = new javax.swing.GroupLayout(jRoomCharges);
        jRoomCharges.setLayout(jRoomChargesLayout);
        jRoomChargesLayout.setHorizontalGroup(
            jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRoomChargesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(58, 58, 58)
                .addGroup(jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDoctorFees, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPatientID1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jRoomChargesLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPathology, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jRoomChargesLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jMiscellanous, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jRoomChargesLayout.setVerticalGroup(
            jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRoomChargesLayout.createSequentialGroup()
                .addGroup(jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRoomChargesLayout.createSequentialGroup()
                        .addGroup(jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jRoomChargesLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRoomChargesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPatientID1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRoomChargesLayout.createSequentialGroup()
                        .addGroup(jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPathology, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)))
                .addGroup(jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jDoctorFees, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jRoomChargesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jRoomChargesLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel28))
                        .addComponent(jMiscellanous, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jRoomCharges);
        jRoomCharges.setBounds(230, 350, 960, 150);

        jLabel26.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel26.setText("Room Charges");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(230, 520, 130, 25);

        jPatientID2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jPatientID2);
        jPatientID2.setBounds(440, 510, 210, 40);

        jTotalButton.setBackground(new java.awt.Color(153, 255, 255));
        jTotalButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTotalButton.setText("Total");
        jTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jTotalButton);
        jTotalButton.setBounds(680, 510, 130, 40);

        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel17.setText("Date");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(770, 100, 90, 25);

        jDate.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jDate);
        jDate.setBounds(960, 100, 210, 40);

        jBillNumber.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jBillNumber);
        jBillNumber.setBounds(460, 100, 210, 40);

        jLabel27.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel27.setText("Bill No");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(230, 90, 90, 25);

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(120, 110, 10, 440);

        jPanel6.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(1270, 120, 10, 420);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenderComboBoxActionPerformed
        /* if ( jComboBox1.getSelectedItem().equals("Panado")){
            jReferenceNo.setText("Pan238371");
            jDailyDose.setText("3");
            jDose.setText("6");
            jNumberofTablets.setText("24");
            jExpDate.setText("05/7/2025");
            jInformation.setText("Place Dispensary");
            jSideEffect.setText("Laziness");
            jIssuedDate.setText("19/04/2021");
            jInstructions.setText("Take one after 3 hours");
            jStorage.setText("Store in cool dry place");
            jLOT.setText("474743");
            jMachines.setText("No");
            jNFS.setText("489483");
            jDateOfBirth.setText("");
            jPatientAddress.setText("");
            jPatientID.setText("");
            jPatientName.setText("");

        }

        else if (jComboBox1.getSelectedItem().equals("Selection")){
            jReferenceNo.setText("");
            jDailyDose.setText("");
            jDose.setText("");
            jNumberofTablets.setText("");
            jExpDate.setText("");
            jInformation.setText("");
            jSideEffect.setText("");
            jIssuedDate.setText("");
            jInstructions.setText("");
            jStorage.setText("");
            jLOT.setText("");
            jMachines.setText("");
            jNFS.setText("");
            jDateOfBirth.setText("");
            jPatientAddress.setText("");
            jPatientID.setText("");
            jPatientName.setText("");
            jPrintTextArea1.setText("");
        }

        else if (jComboBox1.getSelectedItem().equals("Ibuprofen")){
            jReferenceNo.setText("Ibru737373");
            jDailyDose.setText("2");
            jDose.setText("4");
            jNumberofTablets.setText("12");
            jExpDate.setText("12/12/2023");
            jInformation.setText("Place Dispensary");
            jSideEffect.setText("Bleeding");
            jIssuedDate.setText("14/04/2021");
            jInstructions.setText("Use water only");
            jStorage.setText("Cool, Dry place");
            jLOT.setText("383922");
            jMachines.setText("No");
            jNFS.setText("484983");
            jDateOfBirth.setText("");
            jPatientAddress.setText("");
            jPatientID.setText("");
            jPatientName.setText("");
        }

        else if (jComboBox1.getSelectedItem().equals("Paracetemol")){
            jReferenceNo.setText("Par7373");
            jDailyDose.setText("4");
            jDose.setText("12");
            jNumberofTablets.setText("24");
            jExpDate.setText("02/04/2023");
            jInformation.setText("Place Dispensary");
            jSideEffect.setText("Dizziness");
            jIssuedDate.setText("11/05/2021");
            jInstructions.setText("Use water only");
            jStorage.setText("Cool, Dry place");
            jLOT.setText("47922");
            jMachines.setText("No");
            jNFS.setText("147393");
            jDateOfBirth.setText("");
            jPatientAddress.setText("");
            jPatientID.setText("");
            jPatientName.setText("");
        }

        else {
            jReferenceNo.setText("Gr87373");
            jDailyDose.setText("2");
            jDose.setText("6");
            jNumberofTablets.setText("18");
            jExpDate.setText("02/10/2022");
            jInformation.setText("Place Dispensary");
            jSideEffect.setText("Dizziness");
            jIssuedDate.setText("07/04/2021");
            jInstructions.setText("Use water only");
            jStorage.setText("Cool, Dry place");
            jLOT.setText("5832");
            jMachines.setText("No");
            jNFS.setText("409383");
            jDateOfBirth.setText("");
            jPatientAddress.setText("");
            jPatientID.setText("");
            jPatientName.setText("");
        }*/
    }//GEN-LAST:event_jGenderComboBoxActionPerformed

    private void jTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalButtonActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confrim if you want to exit", "Hospital Management Systems",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            mainmenu main = new mainmenu();
            this.setVisible(false);
            main.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTotalButtonActionPerformed

    private void jCloseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseButton1ActionPerformed
        mainmenu m = new mainmenu();
        this.setVisible(false);
        m.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jCloseButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inpatientbillingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inpatientbillingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inpatientbillingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inpatientbillingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inpatientbillingform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JTextField jBillNumber;
    private javax.swing.JButton jCloseButton1;
    private javax.swing.JTextField jDate;
    private javax.swing.JTextField jDateOfAdmission;
    private javax.swing.JTextField jDateOfDischarge;
    private javax.swing.JTextField jDoctorFees;
    private javax.swing.JComboBox<String> jGenderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JTextField jMiscellanous;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jPathology;
    private javax.swing.JTextField jPatientAge;
    private javax.swing.JTextField jPatientID;
    private javax.swing.JTextField jPatientID1;
    private javax.swing.JTextField jPatientID2;
    private javax.swing.JTextField jPatientName;
    private javax.swing.JTable jPatientTable;
    private javax.swing.JPanel jRoomCharges;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jTotalButton;
    // End of variables declaration//GEN-END:variables
}
