/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tunki
 */
public class outpatient extends javax.swing.JFrame {
    
    private JFrame frame;
    Connection conn;

    /**
     * Creates new form inpatient
     */
    public outpatient() {
        initComponents();
        conn = DBConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jContactNo = new javax.swing.JTextField();
        jdoctorName = new javax.swing.JTextField();
        jPatientAge = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPatientID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jDepartmentComboBox = new javax.swing.JComboBox<>();
        jPatientName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDate = new javax.swing.JTextField();
        jGenderComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OUTPATIENT REGISTRATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 20, 550, 60);

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel16.setText("Contact No");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(740, 190, 120, 25);

        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel18.setText("Department");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(240, 340, 130, 25);

        jLabel20.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel20.setText("Doctor Name");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(240, 390, 130, 25);

        jLabel19.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel19.setText("Gender");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(240, 290, 63, 25);

        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel21.setText("Age");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(240, 240, 35, 25);

        jLabel22.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel22.setText("Name");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(240, 190, 51, 25);

        jContactNo.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jContactNo);
        jContactNo.setBounds(910, 180, 210, 40);

        jdoctorName.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jdoctorName);
        jdoctorName.setBounds(440, 380, 210, 40);

        jPatientAge.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jPatientAge);
        jPatientAge.setBounds(440, 230, 210, 40);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1370, 5));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 80, 1370, 10);

        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel17.setText("Patient ID");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(240, 140, 87, 25);

        jPatientID.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jPatientID);
        jPatientID.setBounds(440, 130, 210, 40);

        jLabel23.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel23.setText("Date");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(740, 140, 41, 25);

        jDepartmentComboBox.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jDepartmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "the", "best", "stupid" }));
        jDepartmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepartmentComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jDepartmentComboBox);
        jDepartmentComboBox.setBounds(440, 330, 210, 40);

        jPatientName.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jPatientName);
        jPatientName.setBounds(440, 180, 210, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Save");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(240, 20, 130, 40);

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(400, 20, 130, 40);

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(560, 20, 130, 40);

        jButton6.setBackground(new java.awt.Color(153, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(730, 20, 130, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 450, 1370, 70);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Department", "Doctor Name", "Date", "Contact No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 530, 810, 150);

        jDate.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jDate);
        jDate.setBounds(910, 130, 210, 40);

        jGenderComboBox.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female" }));
        jGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenderComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jGenderComboBox);
        jGenderComboBox.setBounds(440, 280, 210, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/health-2082630.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-70, 0, 1440, 770);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDepartmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepartmentComboBoxActionPerformed
        /* if ( jComboBox1.getSelectedItem().equals("Panado")){
            jReferenceNo.setText("Pan238371");
            jDailyDose.setText("3");
            jDose.setText("6");
            jNumberofTablets.setText("24");
            jExpDate.setText("05/7/2025");
            jInformation.setText("Place Dispensary");
            jSideEffect.setText("Laziness");
            jIssuedDate.setText("19/04/2021");
            jInstructions.setText("Take one after 3 hours");
            jStorage.setText("Store in cool dry place");
            jLOT.setText("474743");
            jMachines.setText("No");
            jNFS.setText("489483");
            jDateOfBirth.setText("");
            jPatientAddress.setText("");
            jPatientID.setText("");
            jPatientName.setText("");

        }

        else if (jComboBox1.getSelectedItem().equals("Selection")){
            jReferenceNo.setText("");
            jDailyDose.setText("");
            jDose.setText("");
            jNumberofTablets.setText("");
            jExpDate.setText("");
            jInformation.setText("");
            jSideEffect.setText("");
            jIssuedDate.setText("");
            jInstructions.setText("");
            jStorage.setText("");
            jLOT.setText("");
            jMachines.setText("");
            jNFS.setText("");
            jDateOfBirth.setText("");
            jPatientAddress.setText("");
            jPatientID.setText("");
            jPatientName.setText("");
            jPrintTextArea1.setText("");
        }

        else if (jComboBox1.getSelectedItem().equals("Ibuprofen")){
            jReferenceNo.setText("Ibru737373");
            jDailyDose.setText("2");
            jDose.setText("4");
            jNumberofTablets.setText("12");
            jExpDate.setText("12/12/2023");
            jInformation.setText("Place Dispensary");
            jSideEffect.setText("Bleeding");
            jIssuedDate.setText("14/04/2021");
            jInstructions.setText("Use water only");
            jStorage.setText("Cool, Dry place");
            jLOT.setText("383922");
            jMachines.setText("No");
            jNFS.setText("484983");
            jDateOfBirth.setText("");
            jPatientAddress.setText("");
            jPatientID.setText("");
            jPatientName.setText("");
        }

        else if (jComboBox1.getSelectedItem().equals("Paracetemol")){
            jReferenceNo.setText("Par7373");
            jDailyDose.setText("4");
            jDose.setText("12");
            jNumberofTablets.setText("24");
            jExpDate.setText("02/04/2023");
            jInformation.setText("Place Dispensary");
            jSideEffect.setText("Dizziness");
            jIssuedDate.setText("11/05/2021");
            jInstructions.setText("Use water only");
            jStorage.setText("Cool, Dry place");
            jLOT.setText("47922");
            jMachines.setText("No");
            jNFS.setText("147393");
            jDateOfBirth.setText("");
            jPatientAddress.setText("");
            jPatientID.setText("");
            jPatientName.setText("");
        }

        else {
            jReferenceNo.setText("Gr87373");
            jDailyDose.setText("2");
            jDose.setText("6");
            jNumberofTablets.setText("18");
            jExpDate.setText("02/10/2022");
            jInformation.setText("Place Dispensary");
            jSideEffect.setText("Dizziness");
            jIssuedDate.setText("07/04/2021");
            jInstructions.setText("Use water only");
            jStorage.setText("Cool, Dry place");
            jLOT.setText("5832");
            jMachines.setText("No");
            jNFS.setText("409383");
            jDateOfBirth.setText("");
            jPatientAddress.setText("");
            jPatientID.setText("");
            jPatientName.setText("");
        }*/
    }//GEN-LAST:event_jDepartmentComboBoxActionPerformed

    private void jGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGenderComboBoxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confrim if you want to exit", "Hospital Management Systems",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            mainmenu main = new mainmenu();
            this.setVisible(false);
            main.setVisible(true);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        outpatientsearch search = new outpatientsearch();
        search.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Name, ID, Age, Gender, Contact, Date, Doctor, Department;
        
        Name = jPatientName.getText();
        ID = jPatientID.getText();
        Age = jPatientAge.getText();
        Gender = jGenderComboBox.getSelectedItem().toString();
        Department = jDepartmentComboBox.getSelectedItem().toString();
        Contact = jContactNo.getText();
        Doctor = jdoctorName.getText();
        Date = jDate.getText();
        if (Name.isEmpty() && ID.isEmpty() && Age.isEmpty() && jGenderComboBox.getSelectedItem().equals("")
            && jDepartmentComboBox.getSelectedItem().equals("") && Contact.isEmpty() && Doctor.isEmpty() && Date.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter all required information", "Hospital Management Systemt", JOptionPane.OK_OPTION);
        }
        else {
        try {
            String st = "INSERT INTO `outpatient`(`name`,`id`, "
                    + "`age`, `gender`, `department`, `contact`, `date`, `doctor`)"
                    + " VALUES ('" + Name + "', '" + ID + "', '" + Age + "', '" + Gender + "',"
                    + " '" + Department + "', '" + Contact + "', '" + Date + "', '" + Doctor + "')";
            PreparedStatement sql = conn.prepareStatement(st);
            sql.execute();
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{ID, Name, Age, Gender,
                Department, Doctor, Date, Contact});
            
            JOptionPane.showMessageDialog(null, "Successfull");
            
            jPatientID.setText("");
            jPatientName.setText("");
            jPatientAge.setText("");
            jGenderComboBox.getSelectedItem().equals("");
            jDepartmentComboBox.getSelectedItem().equals("");
            jContactNo.setText("");
            jDate.setText("");
            jdoctorName.setText("");

            // TODO add your handling code here:*
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }   }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No Data to delete", "Hospital Management System", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Select row to delete", "Hospital Management System", JOptionPane.OK_OPTION);
            }
        } else if (JOptionPane.showConfirmDialog(frame, "Confrim if you want to Delete this row", "Hospital Management Systems",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            model.removeRow(jTable1.getSelectedRow());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(outpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(outpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(outpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(outpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new outpatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jContactNo;
    private javax.swing.JTextField jDate;
    private javax.swing.JComboBox<String> jDepartmentComboBox;
    private javax.swing.JComboBox<String> jGenderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPatientAge;
    private javax.swing.JTextField jPatientID;
    private javax.swing.JTextField jPatientName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jdoctorName;
    // End of variables declaration//GEN-END:variables
}
