/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement;

import static java.lang.System.out;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tunki
 */
public class outpatientsearch extends javax.swing.JFrame {

    private JFrame frame;
    Connection conn;
    /**
     * Creates new form inpatient
     */
    public outpatientsearch() {
        initComponents();
        conn = DBConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jAddButton = new javax.swing.JButton();
        jCloseButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jSearch = new javax.swing.JTextField();
        jSearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jIpSearch = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IP SEARCH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 620, 60);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1370, 5));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 80, 1370, 10);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jAddButton.setBackground(new java.awt.Color(204, 255, 255));
        jAddButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jAddButton.setText("Delete");
        jAddButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });
        jPanel3.add(jAddButton);
        jAddButton.setBounds(30, 20, 130, 40);

        jCloseButton2.setBackground(new java.awt.Color(153, 255, 255));
        jCloseButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCloseButton2.setText("Exit");
        jCloseButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCloseButton2);
        jCloseButton2.setBounds(220, 20, 130, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(110, 430, 380, 70);

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSearch.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        jSearchButton.setBackground(new java.awt.Color(153, 255, 255));
        jSearchButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSearchButton.setText("Search");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 100, 580, 70);

        jIpSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIpSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age", "Gender"
            }
        ));
        jScrollPane1.setViewportView(jIpSearch);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 220, 580, 160);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
 String name = jSearch.getText();
        String Name, ID, Age, Gender, Contact, Date, Department, Doctor;
         
           DBConnect db = new DBConnect();
        try (Connection conn = db.connect()){
           //String state = "select * from login where username =? and password = ?"; 
            PreparedStatement sql = conn.prepareStatement("select * from outpatient where name =?");
            sql.setString(1, name);
            ResultSet rs = sql.executeQuery();
            if(rs.next()){
              Name = rs.getString("name");
              ID = rs.getString("id");
              Age = rs.getString("age");
              Gender = rs.getString("gender");
              Contact = rs.getString("contact");
              Date = rs.getString("date");
              Department = rs.getString("department");
              Doctor = rs.getString("doctor");
              
                DefaultTableModel model = (DefaultTableModel) jIpSearch.getModel();
                model.addRow(new Object[]{ID, Name, Age, Gender});
                      
           
            }
            else{
            JOptionPane.showMessageDialog(null,"Record was not found");
            }
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jCloseButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseButton2ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jCloseButton2ActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
 DefaultTableModel model = (DefaultTableModel) jIpSearch.getModel();
        if (jIpSearch.getSelectedRow() == -1) {
            if (jIpSearch.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No Data to delete", "Hospital Management System", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Select row to delete", "Hospital Management System", JOptionPane.OK_OPTION);
            }
        } else if (JOptionPane.showConfirmDialog(frame, "Confrim if you want to Delete this row", "Hospital Management Systems",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            int row = jIpSearch.getSelectedRow();
            String id = jIpSearch.getModel().getValueAt(row, 0).toString();
            out.print(id);
            String del = "delete from inpatient where id =?";

            try {
                PreparedStatement st = conn.prepareStatement(del);
                st.setString(1, id);
                st.execute();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            model.removeRow(jIpSearch.getSelectedRow());

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(outpatientsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(outpatientsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(outpatientsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(outpatientsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new outpatientsearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jCloseButton2;
    private javax.swing.JTable jIpSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearch;
    private javax.swing.JButton jSearchButton;
    // End of variables declaration//GEN-END:variables
}
