/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author tunki
 */
public class room extends javax.swing.JFrame {

    private JFrame frame;
    Connection conn;

    /**
     * Creates new form inpatient
     */
    public room() {
        initComponents();
        conn = DBConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jRoomNo = new javax.swing.JTextField();
        jRoomType = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jAddButton = new javax.swing.JButton();
        jExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROOM INFORMATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 540, 60);

        jLabel22.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel22.setText("Room Type");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(60, 200, 120, 25);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1370, 5));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 80, 1370, 10);

        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel17.setText("Room NO");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(60, 150, 100, 25);

        jRoomNo.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jRoomNo);
        jRoomNo.setBounds(220, 140, 210, 40);

        jRoomType.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jPanel1.add(jRoomType);
        jRoomType.setBounds(220, 190, 210, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jAddButton.setBackground(new java.awt.Color(204, 255, 255));
        jAddButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jAddButton.setText("Add");
        jAddButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });
        jPanel3.add(jAddButton);
        jAddButton.setBounds(60, 20, 130, 40);

        jExitButton.setBackground(new java.awt.Color(153, 255, 255));
        jExitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });
        jPanel3.add(jExitButton);
        jExitButton.setBounds(240, 20, 130, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 250, 480, 70);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confrim if you want to exit", "Hospital Management Systems",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            mainmenu main = new mainmenu();
            this.setVisible(false);
            main.setVisible(true);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        String RoomNo, RoomType;

        RoomNo = jRoomNo.getText();
        RoomType = jRoomType.getText();

        try {
            String st = "INSERT INTO `room`(`room_no`,`room_type`)"
                    + " VALUES ('" + RoomNo + "', '" + RoomType + "')";
            PreparedStatement sql = conn.prepareStatement(st);
            sql.execute();
            JOptionPane.showMessageDialog(null, "Successfull recorded");
            jRoomNo.setText("");
            jRoomType.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Room Already Recorded");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jExitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jRoomNo;
    private javax.swing.JTextField jRoomType;
    // End of variables declaration//GEN-END:variables
}
